# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 815b52936a9ca63e24d75674d45dbddf977200fe309dc5f36bd6598c0c2d442fde8348bad6bb72142aaeb4d99e8e31e308d255ae2a08abc2cd46a6bb71fd447e

test:
  secret_key_base: 25cb827ce989c7f7d9e7fb99c990bb05997d1eec1c4d895d2bdae7d0442a3787769cdb7418069c86bee917e0313c401554e488422ae0b5107f9bf7e2459ac724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
